name: schemachange_deploy

# Triggers the action based on branch and path. 
on:
  push:
    branches: [dev]
    #paths: ['scripts/**']

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out repo under $GITHUB_WORKSPACE
      - name: Retrieve repository
        uses: actions/checkout@v4

      - name: Use Python 3.12.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.12.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute schemachange
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          schemachange --dry-run \
          -f $GITHUB_WORKSPACE/scripts \
          -a $SNOWFLAKE_ACCOUNT \
          -u $SNOWFLAKE_USERNAME \
          -r $SNOWFLAKE_ROLE \
          -w $SNOWFLAKE_WAREHOUSE \
          -d $SNOWFLAKE_DATABASE \
          -c $SNOWFLAKE_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table